### ISSUE TITLE
Unique tags enforced across iOS `strings` and `stringsdict` files

### ISSUE THREAD

**Issue by richieshilton** [applanga/applanga-cli#1] opened 2024-12-08 23:54 UTC
Hi,

We're having an issue with pushing iOS translations as of the Applanga CLI version `1.0.101`.

In this update, new errors are handled, including enforcing tag uniqueness across localisation files, via `def testTagConflict(config_data)`, [here](https://github.com/applanga/applanga-cli/commit/810af5102b39013dbeda0c273cc43aa70f9913a1#diff-c08f85c8bc8b4fa225ce405d19ef4cfd9897d66111c98913231cc208aadb7b32R138). The issue is that according to the Applanga [docs](https://www.applanga.com/docs/integration-documentation/cli#configuration), iOS strings and stringsdict (standard and plural localization) files are required to have the same tag: "A .stringsdict file always needs an accompanying .strings file so you can use the same tag for both.".

I believe this is the cause of out CICD error: `The tag "xxxx" is used across multiple files for the language "en" in your push block. Please ensure tags are unique per file`.

Can you please let me know if there's a way around this, or if it's a configuration error on our side? 

Thanks

**Comment by cseehausen** [comment] 2024-12-09 10:27
Hello, 
Thank you for reaching out and thank you for the good analysing. You are right and you discovered a case we somehow overlooked during planning of this.

For now i am advicing you to downgrade back to 1.0.93, so it works normally for you again. If you need help for downgrading feel free to write here. 

I will work on adressing this issue within today locally and we should be most likely be able to have a fix deployed for you within tomorrow. I will notify you here when you can upgrade to have it adressed. 

Ty

**Comment by richieshilton** [comment] 2024-12-09 21:55
Thanks for the reply @cseehausen. Can you please advise on downgrading to 1.0.93 - brew doesn't seem to be able to find it. 

I'm using 

```
brew tap applanga/cli
brew install applanga@1.0.93
```

which leads to the error: `Warning: No available formula with the name "applanga@1.0.93". Did you mean applanga?`

**Comment by cseehausen** [comment] 2024-12-10 13:48
Hello, you seem to be discovering all the issues, the versioning in our brew tap is not working properly and we will adress this within the year to be improved so that later version can still be checked out / installed.

You could downgrade manually, but gladly this should not be needed anymore since we just released the fix for your issue so doing an
`brew upgrade`
should raise your cli to 1.0.103 and then it should just work as before.

If you dicover something else feel free to follow up on this, otherwise i will close this issue withing the next couple of days so you have time to check.
Ty

**Comment by cseehausen** [comment] 2024-12-13 13:36
Hello, since there is no response i am guessing the issue is resolved so closing this for now if you encounter any other issues feel free to file another issue, or message us any other way.

Thank you for the flagging again, and have a nice weekend

**Closed as completed by cseehausen** 2024-12-13 13:36 UTC
